services:

  redis:
    image: redis:7-alpine
    volumes:
      - ./volumes/redis:/data
    command: >
      redis-server
      --appendonly yes
      --save 60 1
      --dir /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${INTERNAL_PORT:-8000}
    volumes:
      - .:/app
    ports:
      - "${EXTERNAL_PORT:-8000}:${INTERNAL_PORT:-8000}"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped