services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${INTERNAL_PORT:-8000}
    volumes:
      - .:/app
    ports:
      - "${EXTERNAL_PORT:-8000}:${INTERNAL_PORT:-8000}"
    environment:
      - rabbitmq_host=rabbitmq
      - rabbitmq_port=5672
      - rabbitmq_user=${RABBITMQ_USER:-guest}
      - rabbitmq_password=${RABBITMQ_PASSWORD:-guest}
      - rabbitmq_vhost=${RABBITMQ_VHOST:-/}
    depends_on:
      rabbitmq:
        condition: service_started
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info -E
    volumes:
      - .:/app
    environment:
      - rabbitmq_host=rabbitmq
      - rabbitmq_port=5672
      - rabbitmq_user=${RABBITMQ_USER:-guest}
      - rabbitmq_password=${RABBITMQ_PASSWORD:-guest}
      - rabbitmq_vhost=${RABBITMQ_VHOST:-/}
    depends_on:
      rabbitmq:
        condition: service_started
    restart: unless-stopped

  flower:
    build: .
    command: celery -A app.tasks.celery_app flower --loglevel=info --port=5555 -E
    volumes:
      - .:/app
    environment:
      - FLOWER_BASIC_AUTH=admin:O00k0~QDK8
      - rabbitmq_host=rabbitmq
      - rabbitmq_port=5672
      - rabbitmq_user=${RABBITMQ_USER:-guest}
      - rabbitmq_password=${RABBITMQ_PASSWORD:-guest}
      - rabbitmq_vhost=${RABBITMQ_VHOST:-/}
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_started
    restart: unless-stopped

volumes:
  rabbitmq_data:
