services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    command: postgres -c log_statement=all
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    command: >
      redis-server
      --appendonly yes
      --save 60 1
      --dir /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}
    volumes:
      - .:/app
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped